### ISSUE TITLE
"Authentication Method does not implment IAuthenticationAdapter interface"

### ISSUE THREAD

**Issue by mscott83** [ahelland/ADFSMFAAdapters#2]
I'm trying to install the YubiKey MFA adapter in a lab environment. I've compiled the DLL, registered it with the GAC, and now I'm trying to register it with ADFS but I get the following error:

```
$regstring = ADFSMFAAdapters.YubiKeyMFAAdapter, YubiKeyMFAAdapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=152696276e8615ae
$shortclassname = "YubiKeyMFAAdapter"
Register-AdfsAuthenticationProvider -TypeName $regstring -Name $shortclassname

Register-AdfsAuthenticationProvider : The authentication method ADFSMFAAdapters.YubiKeyMFAAdapter, YubiKeyMFAAdapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=152696276e8615ae does not implement the IAuthenticationAdapter interface.
At line:36 char:1
+ Register-AdfsAuthenticationProvider -TypeName $regstring -Name $shortclassname
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-AdfsAuthenticationProvider], AuthenticationMethodLoadException
    + FullyQualifiedErrorId : The authentication method ADFSMFAAdapters.YubiKeyMFAAdapter, YubiKeyMFAAdapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=152696276e8615ae does not implement the IAuthenticationAdapter interface.,Microsoft.IdentityServer.Management.Commands.AddExternalAuthProviderCommand 
```

**Comment by ahelland** [comment]
Not able to repro here - works like it should on my ADFS box. (It implements the IAuthenticationAdapter interface, so weird how that would show up.)

Assuming it's just a copy&paste error that $regstring doesn't include quotation marks - "ADFSMFAAdapters..." (It fails like it should if I omit this.)

Running PowerShell as admin I assume? (Well, you probably wouldn't be able to get the dll into the GAC if not.)

Which build level is your server?

**Comment by russcook** [comment]
I am having this exact same issue on Windows Server 2012 R2 (Version 6.3 Build 9600).
Any assistance would be appreciated.

-----------------------------------------------------------------------------------------------------------
PS C:\YubikeyADFS> $typeName = "ADFSMFAAdapters.YubiKeyMFAAdapter, YubiKeyMFAAdapter, Version=1.0.0.0, Culture=neutral,PublicKeyToken=152696276e8615ae, processorArchitecture=MSIL"
PS C:\YubikeyADFS> Register-AdfsAuthenticationProvider -TypeName $typeName -Name "YubiKeyMFAAdapter" -ConfigurationFilePath "C:\YubikeyADFS\YubiKeyMFAAdapter.json"
Register-AdfsAuthenticationProvider : The authentication method ADFSMFAAdapters.YubiKeyMFAAdapter, YubiKeyMFAAdapter,Version=1.0.0.0, Culture=neutral, PublicKeyToken=152696276e8615ae, processorArchitecture=MSIL does not implement theIAuthenticationAdapter interface. At line:1 char:1
+ Register-AdfsAuthenticationProvider -TypeName $typeName -Name "YubiKeyMFAAdapter ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-AdfsAuthenticationProvider], AuthenticationMethodLoadException
    + FullyQualifiedErrorId : The authentication method ADFSMFAAdapters.YubiKeyMFAAdapter, YubiKeyMFAAdapter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=152696276e8615ae, processorArchitecture=MSIL does not implement the IAuthenticationAdapter interface.,Microsoft.IdentityServer.Management.Commands.AddExternalAuthProviderCommand

**Comment by russcook** [comment]
I was able to resolve this issue by replacing "Microsoft.IdentityServer.Web.dll" with the version that was preinstalled on my ADFS server instead of the one provided in your source tree.

**Comment by ahelland** [comment]
Ah, I think I know what's up here now.
This solution was built and tested on Windows Server 2016, so I used the dll on the server (which is the recommended way to get ahold of it). The 2016 dll is apparently not friendly with ADFS on 2012 R2.

It could be I should include the old dll in the repo as well just to be sure. I'll have to see if I still have a 2012 R2 ADFS around to verify as well.

I'm in the process of upgrading my ADFS setup at the moment and will probably move this to VS 2017 at the same time - not that it should make a difference for this issue though :)
