### ISSUE TITLE
Yubi authentication doesn't pass through

### ISSUE THREAD

**Issue by BoerelzZ** [ahelland/ADFSMFAAdapters#3]
Hello,

Do you have a more specific documentation on how to use the MFA adapter?

I've downloaded the code and just built the solution in Visual Studio. The DDL was generated without any problems and I was able to add the MFA adapter to my ADFS farm.

I've extracted my yubikey ID (have yubikey 5 NFC) and added this to my user in AD (extension attrib 10)

Even though both ID's match, I still get the error that they don't match.

I also notice that the JSON file included has 2 parameters included
{
  "authId": "",
  "apiKey": "",
  "server": "https://api.yubico.com/wsapi/2.0/verify"
}

Where can i get those parameters?

Thank you in advance,

Kristof

**Comment by ClosedCondition** [comment]
authId and apiKey you are getting from here: [https://upgrade.yubico.com/getapikey/](url)

there are other issues with the code, but eventually, I made it work.
I'll post these separately in issues

**Comment by ahelland** [comment]
ClosedCondition is correct about where to get the key (and id). This was originally documented in a different place, so I'll update the README to call this out.
