### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by mimanu** [ahelland/ADFSMFAAdapters#8]
hi,

I'm trying to follow the guide to setup on my environment

Is this supposed to be on repo YubiKeyMFAAdapter\YubiKeyMFAAdapter.dll?

![image](https://user-images.githubusercontent.com/41720328/98497686-adfa8700-227f-11eb-8c2c-0bbca17d0494.png)

Also the configuration file. I need to have an account and Yubikey on hand? cause i was to setup environment client has the key

**Comment by huffmanaCGB** [comment]
@mimanu You have to compile and build YubiKeyMFAAdapter.csproj.  This will take the Microsoft.IdentityServer.Web.dll either from the repo or the one you replaced it from your ADFS server and create the YubiKeyMFAAdapter.dll.  You need to build it use Visual Studio.
