### ISSUE TITLE
YubiKey method doesn't appear in the list of primary authentication methods

### ISSUE THREAD

**Issue by DJBenson** [ahelland/ADFSMFAAdapters#9]
I've cloned and compiled the code against the version of Microsoft.IdentityServer.Web from my version of Windows (Server 2016 (1607)) and the PowerShell install process goes without issue but the YubiKey method is not available in the list of primary authentication methods, only in the "Multi-factor" tab.

Do you have any idea why?

![image](https://user-images.githubusercontent.com/1013909/102267369-b2b2fa80-3f11-11eb-9fde-d3baa95e07ad.png)

![image](https://user-images.githubusercontent.com/1013909/102267422-c8c0bb00-3f11-11eb-95d0-077d8af76e42.png)

**Comment by ahelland** [comment]
Enabling external auth providers as primary methods requires Windows Server 2019:
[What's new in ADFS 2019](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
